from pathlib import Path

KAFKA_BROKER = "localhost:9092"
RAW_TOPIC = "raw"
PROCESSED_TOPIC = "processed"

RAW_TOPIC_PARTITIONS = 12
PROCESSED_TOPIC_PARTITIONS = 6

BAR_INTERVAL_SEC = 60
SNAPSHOT_INTERVAL_SEC = 1.0

CANDLE_WINDOW_MS = BAR_INTERVAL_SEC * 1000
CANDLE_COUNT = 100

RING_SIZE = 100
MAX_SERIES_POINTS = 300

PROJECT_ROOT = Path(__file__).resolve().parents[2]
STORE_DIR = PROJECT_ROOT / "stored"
RAW_STORE_DIR = STORE_DIR / "raw"
PROCESSED_STORE_DIR = STORE_DIR / "processed"

RAW_FLUSH_SIZE = 2000
PROCESSED_FLUSH_SIZE = 500
FLUSH_INTERVAL_SEC = 5.0

# ---- New market metric + screener config ----
BINANCE_REST_BASE = "https://fapi.binance.com"

GLOBAL_TICK_SEC = 1.0

EMA_ALPHA = 0.2
EMA_BETA = 0.2
EMA_GAMMA = 0.02

MAX_ACTIVE_SYMBOLS = 3
RANGE_LOW = 0.15
RANGE_HIGH = 0.85
MIN_QUOTE_VOLUME_24H = None  # set to float if needed

VOL_STD_WINDOW_COUNT = 60
VOL_REFRESH_SEC = 60.0

FEE_ROUND_TRIP = 0.0010  # 0.10%
SLIP_BUFFER = 0.0005     # 0.05%
VOL_FEE_MULTIPLIER = 2.0

PROMOTION_CONFIRM_SEC = 10.0
PROMOTION_MIN_HOLD_SEC = 60.0

LOG_SCREENING_EVERY_SEC = 30.0
LOG_CANDIDATE_LIMIT = 10

KLINE_INTERVAL = "1m"
KLINE_BOOTSTRAP_COUNT = 99
KELTNER_EMA_LENGTH = 20
KELTNER_ATR_LENGTH = 20
KELTNER_MULTIPLES = [1.0, 1.5, 2.0, 2.5, 3.0]

AGG_TRADE_CHUNK_SIZE = 50
AGG_TRADE_MIN_CHUNK_SIZE = 10
AGG_TRADE_MAX_FAIL_BEFORE_REDUCE = 3
AGG_TRADE_RECONNECT_SEC = 2.0

PAPER_TRADING_ENABLED = True
PAPER_START_EQUITY = 10000.0
PAPER_MAX_TOTAL_PCT = 0.20
PAPER_MAX_SYMBOL_PCT = 0.07
PAPER_MIN_ACTIVE_BANDS = 1
